CREATE TABLE `STORES` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `UNIDADE` VARCHAR(80),
  `ENDERECO` VARCHAR(100),
  `TELEFONE` VARCHAR(20),
  `EMAIL` VARCHAR(90),
  `HORARIO_ABERTURA` TIME,
  `HORARIO_FECHAMENTO` TIME
);

CREATE TABLE `BOOKS` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NOME` VARCHAR(70),
  `AUTOR` VARCHAR(90),
  `EDITORA` VARCHAR(70),
  `IDIOMA` VARCHAR(40),
  `PAGINAS` INT,
  `ANO` INT,
  `VALOR` DECIMAL(10,2)
);

CREATE TABLE `STOCK` (
  `ID_BOOKS` INT,
  `ID_STORES` INT,
  `QUANTIDADE` INT,
  PRIMARY KEY (`ID_BOOKS`, `ID_STORES`)
);

CREATE TABLE `EMPLOYEES` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NOME` VARCHAR(90),
  `MATRICULA` VARCHAR(10),
  `CARGO` VARCHAR(40),
  `EMAIL` VARCHAR(90),
  `TELEFONE` VARCHAR(20),
  `DATA_DE_NASCIMENTO` DATE,
  `CPF` VARCHAR(14),
  `SENHA` VARCHAR(8),
  `ID_STORES` INT
);

CREATE TABLE `CUSTOMERS` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NOME` VARCHAR(90),
  `EMAIL` VARCHAR(90),
  `TELEFONE` VARCHAR(20),
  `DATA_DE_NASCIMENTO` DATE,
  `CPF` VARCHAR(14),
  `SENHA` VARCHAR(8)
);

CREATE TABLE `SALES` (
  `ID_CUSTOMERS` INT,
  `ID_BOOKS` INT,
  `QUANTIDADE_ADQUIRIDA` INT,
  `ID_STORES` INT,
  `DATA_COMPRA` DATE,
  `HORARIO_COMPRA` TIME,
  PRIMARY KEY (`ID_CUSTOMERS`, `ID_BOOKS`, `ID_STORES`)
);

ALTER TABLE `STOCK` ADD FOREIGN KEY (`ID_BOOKS`) REFERENCES `BOOKS` (`ID`);

ALTER TABLE `STOCK` ADD FOREIGN KEY (`ID_STORES`) REFERENCES `STORES` (`ID`);

ALTER TABLE `EMPLOYEES` ADD FOREIGN KEY (`ID_STORES`) REFERENCES `STORES` (`ID`);

ALTER TABLE `SALES` ADD FOREIGN KEY (`ID_CUSTOMERS`) REFERENCES `CUSTOMERS` (`ID`);

ALTER TABLE `SALES` ADD FOREIGN KEY (`ID_BOOKS`) REFERENCES `BOOKS` (`ID`);

ALTER TABLE `SALES` ADD FOREIGN KEY (`ID_STORES`) REFERENCES `STORES` (`ID`);
